// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sync/v1/sync.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Harmony.Sync.V1 {

  /// <summary>Holder for reflection information generated from sync/v1/sync.proto</summary>
  public static partial class SyncReflection {

    #region Descriptor
    /// <summary>File descriptor for sync/v1/sync.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SyncReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJzeW5jL3YxL3N5bmMucHJvdG8SEHByb3RvY29sLnN5bmMudjEiKwoIQXV0",
            "aERhdGESEQoJc2VydmVyX2lkGAEgASgJEgwKBHRpbWUYAiABKAQitwQKBUV2",
            "ZW50Ek8KF3VzZXJfcmVtb3ZlZF9mcm9tX2d1aWxkGAEgASgLMiwucHJvdG9j",
            "b2wuc3luYy52MS5FdmVudC5Vc2VyUmVtb3ZlZEZyb21HdWlsZEgAEkcKE3Vz",
            "ZXJfYWRkZWRfdG9fZ3VpbGQYAiABKAsyKC5wcm90b2NvbC5zeW5jLnYxLkV2",
            "ZW50LlVzZXJBZGRlZFRvR3VpbGRIABI7Cgx1c2VyX2ludml0ZWQYAyABKAsy",
            "Iy5wcm90b2NvbC5zeW5jLnYxLkV2ZW50LlVzZXJJbnZpdGVkSAASSgoUdXNl",
            "cl9yZWplY3RlZF9pbnZpdGUYBCABKAsyKi5wcm90b2NvbC5zeW5jLnYxLkV2",
            "ZW50LlVzZXJSZWplY3RlZEludml0ZUgAGjkKFFVzZXJSZW1vdmVkRnJvbUd1",
            "aWxkEg8KB3VzZXJfaWQYASABKAQSEAoIZ3VpbGRfaWQYAiABKAQaNQoQVXNl",
            "ckFkZGVkVG9HdWlsZBIPCgd1c2VyX2lkGAEgASgEEhAKCGd1aWxkX2lkGAIg",
            "ASgEGkUKC1VzZXJJbnZpdGVkEg8KB3VzZXJfaWQYASABKAQSEgoKaW52aXRl",
            "cl9pZBgCIAEoBBIRCglpbnZpdGVfaWQYAyABKAkaSgoSVXNlclJlamVjdGVk",
            "SW52aXRlEhAKCGd1aWxkX2lkGAEgASgEEg8KB3VzZXJfaWQYAiABKAQSEQoJ",
            "aW52aXRlX2lkGAMgASgJQgYKBGtpbmQiDQoLUHVsbFJlcXVlc3QiPAoMUHVs",
            "bFJlc3BvbnNlEiwKC2V2ZW50X3F1ZXVlGAEgAygLMhcucHJvdG9jb2wuc3lu",
            "Yy52MS5FdmVudCI1CgtQdXNoUmVxdWVzdBImCgVldmVudBgBIAEoCzIXLnBy",
            "b3RvY29sLnN5bmMudjEuRXZlbnQiDgoMUHVzaFJlc3BvbnNlIisKEk5vdGlm",
            "eU5ld0lkUmVxdWVzdBIVCg1uZXdfc2VydmVyX2lkGAEgASgJIhUKE05vdGlm",
            "eU5ld0lkUmVzcG9uc2UygAIKDlBvc3Rib3hTZXJ2aWNlEkcKBFB1bGwSHS5w",
            "cm90b2NvbC5zeW5jLnYxLlB1bGxSZXF1ZXN0Gh4ucHJvdG9jb2wuc3luYy52",
            "MS5QdWxsUmVzcG9uc2UiABJHCgRQdXNoEh0ucHJvdG9jb2wuc3luYy52MS5Q",
            "dXNoUmVxdWVzdBoeLnByb3RvY29sLnN5bmMudjEuUHVzaFJlc3BvbnNlIgAS",
            "XAoLTm90aWZ5TmV3SWQSJC5wcm90b2NvbC5zeW5jLnYxLk5vdGlmeU5ld0lk",
            "UmVxdWVzdBolLnByb3RvY29sLnN5bmMudjEuTm90aWZ5TmV3SWRSZXNwb25z",
            "ZSIAQjNaMWdpdGh1Yi5jb20vaGFybW9ueS1kZXZlbG9wbWVudC9sZWdhdG8v",
            "Z2VuL3N5bmMvdjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.AuthData), global::Harmony.Sync.V1.AuthData.Parser, new[]{ "ServerId", "Time" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.Event), global::Harmony.Sync.V1.Event.Parser, new[]{ "UserRemovedFromGuild", "UserAddedToGuild", "UserInvited", "UserRejectedInvite" }, new[]{ "Kind" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild), global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild.Parser, new[]{ "UserId", "GuildId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.Event.Types.UserAddedToGuild), global::Harmony.Sync.V1.Event.Types.UserAddedToGuild.Parser, new[]{ "UserId", "GuildId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.Event.Types.UserInvited), global::Harmony.Sync.V1.Event.Types.UserInvited.Parser, new[]{ "UserId", "InviterId", "InviteId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.Event.Types.UserRejectedInvite), global::Harmony.Sync.V1.Event.Types.UserRejectedInvite.Parser, new[]{ "GuildId", "UserId", "InviteId" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.PullRequest), global::Harmony.Sync.V1.PullRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.PullResponse), global::Harmony.Sync.V1.PullResponse.Parser, new[]{ "EventQueue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.PushRequest), global::Harmony.Sync.V1.PushRequest.Parser, new[]{ "Event" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.PushResponse), global::Harmony.Sync.V1.PushResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.NotifyNewIdRequest), global::Harmony.Sync.V1.NotifyNewIdRequest.Parser, new[]{ "NewServerId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Harmony.Sync.V1.NotifyNewIdResponse), global::Harmony.Sync.V1.NotifyNewIdResponse.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Authentication data that will be sent in a `harmonytypes.v1.Token`.
  /// </summary>
  public sealed partial class AuthData : pb::IMessage<AuthData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuthData> _parser = new pb::MessageParser<AuthData>(() => new AuthData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AuthData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Harmony.Sync.V1.SyncReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthData(AuthData other) : this() {
      serverId_ = other.serverId_;
      time_ = other.time_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AuthData Clone() {
      return new AuthData(this);
    }

    /// <summary>Field number for the "server_id" field.</summary>
    public const int ServerIdFieldNumber = 1;
    private string serverId_ = "";
    /// <summary>
    /// The server ID of the server initiating the transaction. For Pull,
    /// this tells the server being connected to which homeservers' events it should send.
    /// For Push, this tells the server being connected to which homeservers' events it is
    /// receiving.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServerId {
      get { return serverId_; }
      set {
        serverId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private ulong time_;
    /// <summary>
    /// The UTC UNIX time in seconds of when the request is started. Servers should reject
    /// tokens with a time too far from the current time, at their discretion. A recommended
    /// variance is 1 minute.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AuthData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AuthData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerId != other.ServerId) return false;
      if (Time != other.Time) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerId.Length != 0) hash ^= ServerId.GetHashCode();
      if (Time != 0UL) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ServerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerId);
      }
      if (Time != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ServerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServerId);
      }
      if (Time != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerId);
      }
      if (Time != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AuthData other) {
      if (other == null) {
        return;
      }
      if (other.ServerId.Length != 0) {
        ServerId = other.ServerId;
      }
      if (other.Time != 0UL) {
        Time = other.Time;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServerId = input.ReadString();
            break;
          }
          case 16: {
            Time = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ServerId = input.ReadString();
            break;
          }
          case 16: {
            Time = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Object representing a postbox event.
  /// </summary>
  public sealed partial class Event : pb::IMessage<Event>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Event> _parser = new pb::MessageParser<Event>(() => new Event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Harmony.Sync.V1.SyncReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event(Event other) : this() {
      switch (other.KindCase) {
        case KindOneofCase.UserRemovedFromGuild:
          UserRemovedFromGuild = other.UserRemovedFromGuild.Clone();
          break;
        case KindOneofCase.UserAddedToGuild:
          UserAddedToGuild = other.UserAddedToGuild.Clone();
          break;
        case KindOneofCase.UserInvited:
          UserInvited = other.UserInvited.Clone();
          break;
        case KindOneofCase.UserRejectedInvite:
          UserRejectedInvite = other.UserRejectedInvite.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event Clone() {
      return new Event(this);
    }

    /// <summary>Field number for the "user_removed_from_guild" field.</summary>
    public const int UserRemovedFromGuildFieldNumber = 1;
    /// <summary>
    /// User removed from a guild.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild UserRemovedFromGuild {
      get { return kindCase_ == KindOneofCase.UserRemovedFromGuild ? (global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild) kind_ : null; }
      set {
        kind_ = value;
        kindCase_ = value == null ? KindOneofCase.None : KindOneofCase.UserRemovedFromGuild;
      }
    }

    /// <summary>Field number for the "user_added_to_guild" field.</summary>
    public const int UserAddedToGuildFieldNumber = 2;
    /// <summary>
    /// User added to a guild.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Harmony.Sync.V1.Event.Types.UserAddedToGuild UserAddedToGuild {
      get { return kindCase_ == KindOneofCase.UserAddedToGuild ? (global::Harmony.Sync.V1.Event.Types.UserAddedToGuild) kind_ : null; }
      set {
        kind_ = value;
        kindCase_ = value == null ? KindOneofCase.None : KindOneofCase.UserAddedToGuild;
      }
    }

    /// <summary>Field number for the "user_invited" field.</summary>
    public const int UserInvitedFieldNumber = 3;
    /// <summary>
    /// User invited to a guild.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Harmony.Sync.V1.Event.Types.UserInvited UserInvited {
      get { return kindCase_ == KindOneofCase.UserInvited ? (global::Harmony.Sync.V1.Event.Types.UserInvited) kind_ : null; }
      set {
        kind_ = value;
        kindCase_ = value == null ? KindOneofCase.None : KindOneofCase.UserInvited;
      }
    }

    /// <summary>Field number for the "user_rejected_invite" field.</summary>
    public const int UserRejectedInviteFieldNumber = 4;
    /// <summary>
    /// User rejected a guild invitation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Harmony.Sync.V1.Event.Types.UserRejectedInvite UserRejectedInvite {
      get { return kindCase_ == KindOneofCase.UserRejectedInvite ? (global::Harmony.Sync.V1.Event.Types.UserRejectedInvite) kind_ : null; }
      set {
        kind_ = value;
        kindCase_ = value == null ? KindOneofCase.None : KindOneofCase.UserRejectedInvite;
      }
    }

    private object kind_;
    /// <summary>Enum of possible cases for the "kind" oneof.</summary>
    public enum KindOneofCase {
      None = 0,
      UserRemovedFromGuild = 1,
      UserAddedToGuild = 2,
      UserInvited = 3,
      UserRejectedInvite = 4,
    }
    private KindOneofCase kindCase_ = KindOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KindOneofCase KindCase {
      get { return kindCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearKind() {
      kindCase_ = KindOneofCase.None;
      kind_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UserRemovedFromGuild, other.UserRemovedFromGuild)) return false;
      if (!object.Equals(UserAddedToGuild, other.UserAddedToGuild)) return false;
      if (!object.Equals(UserInvited, other.UserInvited)) return false;
      if (!object.Equals(UserRejectedInvite, other.UserRejectedInvite)) return false;
      if (KindCase != other.KindCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (kindCase_ == KindOneofCase.UserRemovedFromGuild) hash ^= UserRemovedFromGuild.GetHashCode();
      if (kindCase_ == KindOneofCase.UserAddedToGuild) hash ^= UserAddedToGuild.GetHashCode();
      if (kindCase_ == KindOneofCase.UserInvited) hash ^= UserInvited.GetHashCode();
      if (kindCase_ == KindOneofCase.UserRejectedInvite) hash ^= UserRejectedInvite.GetHashCode();
      hash ^= (int) kindCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (kindCase_ == KindOneofCase.UserRemovedFromGuild) {
        output.WriteRawTag(10);
        output.WriteMessage(UserRemovedFromGuild);
      }
      if (kindCase_ == KindOneofCase.UserAddedToGuild) {
        output.WriteRawTag(18);
        output.WriteMessage(UserAddedToGuild);
      }
      if (kindCase_ == KindOneofCase.UserInvited) {
        output.WriteRawTag(26);
        output.WriteMessage(UserInvited);
      }
      if (kindCase_ == KindOneofCase.UserRejectedInvite) {
        output.WriteRawTag(34);
        output.WriteMessage(UserRejectedInvite);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (kindCase_ == KindOneofCase.UserRemovedFromGuild) {
        output.WriteRawTag(10);
        output.WriteMessage(UserRemovedFromGuild);
      }
      if (kindCase_ == KindOneofCase.UserAddedToGuild) {
        output.WriteRawTag(18);
        output.WriteMessage(UserAddedToGuild);
      }
      if (kindCase_ == KindOneofCase.UserInvited) {
        output.WriteRawTag(26);
        output.WriteMessage(UserInvited);
      }
      if (kindCase_ == KindOneofCase.UserRejectedInvite) {
        output.WriteRawTag(34);
        output.WriteMessage(UserRejectedInvite);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (kindCase_ == KindOneofCase.UserRemovedFromGuild) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserRemovedFromGuild);
      }
      if (kindCase_ == KindOneofCase.UserAddedToGuild) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserAddedToGuild);
      }
      if (kindCase_ == KindOneofCase.UserInvited) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserInvited);
      }
      if (kindCase_ == KindOneofCase.UserRejectedInvite) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserRejectedInvite);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Event other) {
      if (other == null) {
        return;
      }
      switch (other.KindCase) {
        case KindOneofCase.UserRemovedFromGuild:
          if (UserRemovedFromGuild == null) {
            UserRemovedFromGuild = new global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild();
          }
          UserRemovedFromGuild.MergeFrom(other.UserRemovedFromGuild);
          break;
        case KindOneofCase.UserAddedToGuild:
          if (UserAddedToGuild == null) {
            UserAddedToGuild = new global::Harmony.Sync.V1.Event.Types.UserAddedToGuild();
          }
          UserAddedToGuild.MergeFrom(other.UserAddedToGuild);
          break;
        case KindOneofCase.UserInvited:
          if (UserInvited == null) {
            UserInvited = new global::Harmony.Sync.V1.Event.Types.UserInvited();
          }
          UserInvited.MergeFrom(other.UserInvited);
          break;
        case KindOneofCase.UserRejectedInvite:
          if (UserRejectedInvite == null) {
            UserRejectedInvite = new global::Harmony.Sync.V1.Event.Types.UserRejectedInvite();
          }
          UserRejectedInvite.MergeFrom(other.UserRejectedInvite);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild subBuilder = new global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild();
            if (kindCase_ == KindOneofCase.UserRemovedFromGuild) {
              subBuilder.MergeFrom(UserRemovedFromGuild);
            }
            input.ReadMessage(subBuilder);
            UserRemovedFromGuild = subBuilder;
            break;
          }
          case 18: {
            global::Harmony.Sync.V1.Event.Types.UserAddedToGuild subBuilder = new global::Harmony.Sync.V1.Event.Types.UserAddedToGuild();
            if (kindCase_ == KindOneofCase.UserAddedToGuild) {
              subBuilder.MergeFrom(UserAddedToGuild);
            }
            input.ReadMessage(subBuilder);
            UserAddedToGuild = subBuilder;
            break;
          }
          case 26: {
            global::Harmony.Sync.V1.Event.Types.UserInvited subBuilder = new global::Harmony.Sync.V1.Event.Types.UserInvited();
            if (kindCase_ == KindOneofCase.UserInvited) {
              subBuilder.MergeFrom(UserInvited);
            }
            input.ReadMessage(subBuilder);
            UserInvited = subBuilder;
            break;
          }
          case 34: {
            global::Harmony.Sync.V1.Event.Types.UserRejectedInvite subBuilder = new global::Harmony.Sync.V1.Event.Types.UserRejectedInvite();
            if (kindCase_ == KindOneofCase.UserRejectedInvite) {
              subBuilder.MergeFrom(UserRejectedInvite);
            }
            input.ReadMessage(subBuilder);
            UserRejectedInvite = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild subBuilder = new global::Harmony.Sync.V1.Event.Types.UserRemovedFromGuild();
            if (kindCase_ == KindOneofCase.UserRemovedFromGuild) {
              subBuilder.MergeFrom(UserRemovedFromGuild);
            }
            input.ReadMessage(subBuilder);
            UserRemovedFromGuild = subBuilder;
            break;
          }
          case 18: {
            global::Harmony.Sync.V1.Event.Types.UserAddedToGuild subBuilder = new global::Harmony.Sync.V1.Event.Types.UserAddedToGuild();
            if (kindCase_ == KindOneofCase.UserAddedToGuild) {
              subBuilder.MergeFrom(UserAddedToGuild);
            }
            input.ReadMessage(subBuilder);
            UserAddedToGuild = subBuilder;
            break;
          }
          case 26: {
            global::Harmony.Sync.V1.Event.Types.UserInvited subBuilder = new global::Harmony.Sync.V1.Event.Types.UserInvited();
            if (kindCase_ == KindOneofCase.UserInvited) {
              subBuilder.MergeFrom(UserInvited);
            }
            input.ReadMessage(subBuilder);
            UserInvited = subBuilder;
            break;
          }
          case 34: {
            global::Harmony.Sync.V1.Event.Types.UserRejectedInvite subBuilder = new global::Harmony.Sync.V1.Event.Types.UserRejectedInvite();
            if (kindCase_ == KindOneofCase.UserRejectedInvite) {
              subBuilder.MergeFrom(UserRejectedInvite);
            }
            input.ReadMessage(subBuilder);
            UserRejectedInvite = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Event message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Event sent when a user is removed from a guild.
      /// </summary>
      public sealed partial class UserRemovedFromGuild : pb::IMessage<UserRemovedFromGuild>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<UserRemovedFromGuild> _parser = new pb::MessageParser<UserRemovedFromGuild>(() => new UserRemovedFromGuild());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<UserRemovedFromGuild> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Harmony.Sync.V1.Event.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRemovedFromGuild() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRemovedFromGuild(UserRemovedFromGuild other) : this() {
          userId_ = other.userId_;
          guildId_ = other.guildId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRemovedFromGuild Clone() {
          return new UserRemovedFromGuild(this);
        }

        /// <summary>Field number for the "user_id" field.</summary>
        public const int UserIdFieldNumber = 1;
        private ulong userId_;
        /// <summary>
        /// User ID of the user that was removed.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong UserId {
          get { return userId_; }
          set {
            userId_ = value;
          }
        }

        /// <summary>Field number for the "guild_id" field.</summary>
        public const int GuildIdFieldNumber = 2;
        private ulong guildId_;
        /// <summary>
        /// Guild ID of the guild where the user was.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong GuildId {
          get { return guildId_; }
          set {
            guildId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as UserRemovedFromGuild);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(UserRemovedFromGuild other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (UserId != other.UserId) return false;
          if (GuildId != other.GuildId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (UserId != 0UL) hash ^= UserId.GetHashCode();
          if (GuildId != 0UL) hash ^= GuildId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (UserId != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(UserId);
          }
          if (GuildId != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(GuildId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (UserId != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(UserId);
          }
          if (GuildId != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(GuildId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (UserId != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
          }
          if (GuildId != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GuildId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(UserRemovedFromGuild other) {
          if (other == null) {
            return;
          }
          if (other.UserId != 0UL) {
            UserId = other.UserId;
          }
          if (other.GuildId != 0UL) {
            GuildId = other.GuildId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                UserId = input.ReadUInt64();
                break;
              }
              case 16: {
                GuildId = input.ReadUInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                UserId = input.ReadUInt64();
                break;
              }
              case 16: {
                GuildId = input.ReadUInt64();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Event sent when a user is added to a guild.
      /// </summary>
      public sealed partial class UserAddedToGuild : pb::IMessage<UserAddedToGuild>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<UserAddedToGuild> _parser = new pb::MessageParser<UserAddedToGuild>(() => new UserAddedToGuild());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<UserAddedToGuild> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Harmony.Sync.V1.Event.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserAddedToGuild() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserAddedToGuild(UserAddedToGuild other) : this() {
          userId_ = other.userId_;
          guildId_ = other.guildId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserAddedToGuild Clone() {
          return new UserAddedToGuild(this);
        }

        /// <summary>Field number for the "user_id" field.</summary>
        public const int UserIdFieldNumber = 1;
        private ulong userId_;
        /// <summary>
        /// User ID of the user that was added.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong UserId {
          get { return userId_; }
          set {
            userId_ = value;
          }
        }

        /// <summary>Field number for the "guild_id" field.</summary>
        public const int GuildIdFieldNumber = 2;
        private ulong guildId_;
        /// <summary>
        /// Guild ID of the guild where the user will be.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong GuildId {
          get { return guildId_; }
          set {
            guildId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as UserAddedToGuild);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(UserAddedToGuild other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (UserId != other.UserId) return false;
          if (GuildId != other.GuildId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (UserId != 0UL) hash ^= UserId.GetHashCode();
          if (GuildId != 0UL) hash ^= GuildId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (UserId != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(UserId);
          }
          if (GuildId != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(GuildId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (UserId != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(UserId);
          }
          if (GuildId != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(GuildId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (UserId != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
          }
          if (GuildId != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GuildId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(UserAddedToGuild other) {
          if (other == null) {
            return;
          }
          if (other.UserId != 0UL) {
            UserId = other.UserId;
          }
          if (other.GuildId != 0UL) {
            GuildId = other.GuildId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                UserId = input.ReadUInt64();
                break;
              }
              case 16: {
                GuildId = input.ReadUInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                UserId = input.ReadUInt64();
                break;
              }
              case 16: {
                GuildId = input.ReadUInt64();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Event sent when a user is invited to a guild.
      /// </summary>
      public sealed partial class UserInvited : pb::IMessage<UserInvited>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<UserInvited> _parser = new pb::MessageParser<UserInvited>(() => new UserInvited());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<UserInvited> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Harmony.Sync.V1.Event.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserInvited() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserInvited(UserInvited other) : this() {
          userId_ = other.userId_;
          inviterId_ = other.inviterId_;
          inviteId_ = other.inviteId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserInvited Clone() {
          return new UserInvited(this);
        }

        /// <summary>Field number for the "user_id" field.</summary>
        public const int UserIdFieldNumber = 1;
        private ulong userId_;
        /// <summary>
        /// User ID of the invitee.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong UserId {
          get { return userId_; }
          set {
            userId_ = value;
          }
        }

        /// <summary>Field number for the "inviter_id" field.</summary>
        public const int InviterIdFieldNumber = 2;
        private ulong inviterId_;
        /// <summary>
        /// User ID of the user that invited.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong InviterId {
          get { return inviterId_; }
          set {
            inviterId_ = value;
          }
        }

        /// <summary>Field number for the "invite_id" field.</summary>
        public const int InviteIdFieldNumber = 3;
        private string inviteId_ = "";
        /// <summary>
        /// The invite for the guild.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string InviteId {
          get { return inviteId_; }
          set {
            inviteId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as UserInvited);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(UserInvited other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (UserId != other.UserId) return false;
          if (InviterId != other.InviterId) return false;
          if (InviteId != other.InviteId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (UserId != 0UL) hash ^= UserId.GetHashCode();
          if (InviterId != 0UL) hash ^= InviterId.GetHashCode();
          if (InviteId.Length != 0) hash ^= InviteId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (UserId != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(UserId);
          }
          if (InviterId != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(InviterId);
          }
          if (InviteId.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(InviteId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (UserId != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(UserId);
          }
          if (InviterId != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(InviterId);
          }
          if (InviteId.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(InviteId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (UserId != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
          }
          if (InviterId != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(InviterId);
          }
          if (InviteId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(InviteId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(UserInvited other) {
          if (other == null) {
            return;
          }
          if (other.UserId != 0UL) {
            UserId = other.UserId;
          }
          if (other.InviterId != 0UL) {
            InviterId = other.InviterId;
          }
          if (other.InviteId.Length != 0) {
            InviteId = other.InviteId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                UserId = input.ReadUInt64();
                break;
              }
              case 16: {
                InviterId = input.ReadUInt64();
                break;
              }
              case 26: {
                InviteId = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                UserId = input.ReadUInt64();
                break;
              }
              case 16: {
                InviterId = input.ReadUInt64();
                break;
              }
              case 26: {
                InviteId = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Event sent when a user rejects a guild invitation.
      /// </summary>
      public sealed partial class UserRejectedInvite : pb::IMessage<UserRejectedInvite>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<UserRejectedInvite> _parser = new pb::MessageParser<UserRejectedInvite>(() => new UserRejectedInvite());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<UserRejectedInvite> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Harmony.Sync.V1.Event.Descriptor.NestedTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRejectedInvite() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRejectedInvite(UserRejectedInvite other) : this() {
          guildId_ = other.guildId_;
          userId_ = other.userId_;
          inviteId_ = other.inviteId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public UserRejectedInvite Clone() {
          return new UserRejectedInvite(this);
        }

        /// <summary>Field number for the "guild_id" field.</summary>
        public const int GuildIdFieldNumber = 1;
        private ulong guildId_;
        /// <summary>
        /// Guild ID of the guild the invitee rejected an invite for.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong GuildId {
          get { return guildId_; }
          set {
            guildId_ = value;
          }
        }

        /// <summary>Field number for the "user_id" field.</summary>
        public const int UserIdFieldNumber = 2;
        private ulong userId_;
        /// <summary>
        /// User ID of the invitee that rejected the invitation.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong UserId {
          get { return userId_; }
          set {
            userId_ = value;
          }
        }

        /// <summary>Field number for the "invite_id" field.</summary>
        public const int InviteIdFieldNumber = 3;
        private string inviteId_ = "";
        /// <summary>
        /// Invite ID of the invite that was rejected.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string InviteId {
          get { return inviteId_; }
          set {
            inviteId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as UserRejectedInvite);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(UserRejectedInvite other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (GuildId != other.GuildId) return false;
          if (UserId != other.UserId) return false;
          if (InviteId != other.InviteId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (GuildId != 0UL) hash ^= GuildId.GetHashCode();
          if (UserId != 0UL) hash ^= UserId.GetHashCode();
          if (InviteId.Length != 0) hash ^= InviteId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (GuildId != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(GuildId);
          }
          if (UserId != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(UserId);
          }
          if (InviteId.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(InviteId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (GuildId != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(GuildId);
          }
          if (UserId != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(UserId);
          }
          if (InviteId.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(InviteId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (GuildId != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GuildId);
          }
          if (UserId != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
          }
          if (InviteId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(InviteId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(UserRejectedInvite other) {
          if (other == null) {
            return;
          }
          if (other.GuildId != 0UL) {
            GuildId = other.GuildId;
          }
          if (other.UserId != 0UL) {
            UserId = other.UserId;
          }
          if (other.InviteId.Length != 0) {
            InviteId = other.InviteId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                GuildId = input.ReadUInt64();
                break;
              }
              case 16: {
                UserId = input.ReadUInt64();
                break;
              }
              case 26: {
                InviteId = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                GuildId = input.ReadUInt64();
                break;
              }
              case 16: {
                UserId = input.ReadUInt64();
                break;
              }
              case 26: {
                InviteId = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  /// <summary>
  /// Used in `Pull` endpoint.
  /// </summary>
  public sealed partial class PullRequest : pb::IMessage<PullRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PullRequest> _parser = new pb::MessageParser<PullRequest>(() => new PullRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PullRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Harmony.Sync.V1.SyncReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullRequest(PullRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullRequest Clone() {
      return new PullRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PullRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PullRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PullRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Used in `Pull` endpoint.
  /// </summary>
  public sealed partial class PullResponse : pb::IMessage<PullResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PullResponse> _parser = new pb::MessageParser<PullResponse>(() => new PullResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PullResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Harmony.Sync.V1.SyncReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullResponse(PullResponse other) : this() {
      eventQueue_ = other.eventQueue_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullResponse Clone() {
      return new PullResponse(this);
    }

    /// <summary>Field number for the "event_queue" field.</summary>
    public const int EventQueueFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Harmony.Sync.V1.Event> _repeated_eventQueue_codec
        = pb::FieldCodec.ForMessage(10, global::Harmony.Sync.V1.Event.Parser);
    private readonly pbc::RepeatedField<global::Harmony.Sync.V1.Event> eventQueue_ = new pbc::RepeatedField<global::Harmony.Sync.V1.Event>();
    /// <summary>
    /// The events that were not processed yet.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Harmony.Sync.V1.Event> EventQueue {
      get { return eventQueue_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PullResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PullResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!eventQueue_.Equals(other.eventQueue_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= eventQueue_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      eventQueue_.WriteTo(output, _repeated_eventQueue_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      eventQueue_.WriteTo(ref output, _repeated_eventQueue_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += eventQueue_.CalculateSize(_repeated_eventQueue_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PullResponse other) {
      if (other == null) {
        return;
      }
      eventQueue_.Add(other.eventQueue_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            eventQueue_.AddEntriesFrom(input, _repeated_eventQueue_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            eventQueue_.AddEntriesFrom(ref input, _repeated_eventQueue_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Used in `Push` endpoint.
  /// </summary>
  public sealed partial class PushRequest : pb::IMessage<PushRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PushRequest> _parser = new pb::MessageParser<PushRequest>(() => new PushRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PushRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Harmony.Sync.V1.SyncReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushRequest(PushRequest other) : this() {
      event_ = other.event_ != null ? other.event_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushRequest Clone() {
      return new PushRequest(this);
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 1;
    private global::Harmony.Sync.V1.Event event_;
    /// <summary>
    /// The event to push to the server.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Harmony.Sync.V1.Event Event {
      get { return event_; }
      set {
        event_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PushRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PushRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Event, other.Event)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (event_ != null) hash ^= Event.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (event_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Event);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (event_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Event);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (event_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Event);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PushRequest other) {
      if (other == null) {
        return;
      }
      if (other.event_ != null) {
        if (event_ == null) {
          Event = new global::Harmony.Sync.V1.Event();
        }
        Event.MergeFrom(other.Event);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (event_ == null) {
              Event = new global::Harmony.Sync.V1.Event();
            }
            input.ReadMessage(Event);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (event_ == null) {
              Event = new global::Harmony.Sync.V1.Event();
            }
            input.ReadMessage(Event);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Used in `Push` endpoint.
  /// </summary>
  public sealed partial class PushResponse : pb::IMessage<PushResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PushResponse> _parser = new pb::MessageParser<PushResponse>(() => new PushResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PushResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Harmony.Sync.V1.SyncReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushResponse(PushResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushResponse Clone() {
      return new PushResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PushResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PushResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PushResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Used in `NotifyNewId` endpoint.
  /// </summary>
  public sealed partial class NotifyNewIdRequest : pb::IMessage<NotifyNewIdRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotifyNewIdRequest> _parser = new pb::MessageParser<NotifyNewIdRequest>(() => new NotifyNewIdRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NotifyNewIdRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Harmony.Sync.V1.SyncReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NotifyNewIdRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NotifyNewIdRequest(NotifyNewIdRequest other) : this() {
      newServerId_ = other.newServerId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NotifyNewIdRequest Clone() {
      return new NotifyNewIdRequest(this);
    }

    /// <summary>Field number for the "new_server_id" field.</summary>
    public const int NewServerIdFieldNumber = 1;
    private string newServerId_ = "";
    /// <summary>
    /// The new server ID of the server.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NewServerId {
      get { return newServerId_; }
      set {
        newServerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NotifyNewIdRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NotifyNewIdRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NewServerId != other.NewServerId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NewServerId.Length != 0) hash ^= NewServerId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NewServerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NewServerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NewServerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NewServerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NewServerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NewServerId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NotifyNewIdRequest other) {
      if (other == null) {
        return;
      }
      if (other.NewServerId.Length != 0) {
        NewServerId = other.NewServerId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NewServerId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            NewServerId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Used in `NotifyNewId` endpoint.
  /// </summary>
  public sealed partial class NotifyNewIdResponse : pb::IMessage<NotifyNewIdResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotifyNewIdResponse> _parser = new pb::MessageParser<NotifyNewIdResponse>(() => new NotifyNewIdResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NotifyNewIdResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Harmony.Sync.V1.SyncReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NotifyNewIdResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NotifyNewIdResponse(NotifyNewIdResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NotifyNewIdResponse Clone() {
      return new NotifyNewIdResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NotifyNewIdResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NotifyNewIdResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NotifyNewIdResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
