name: Integration Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      legato:
        image: spiralsphere/integration-testing-with-legato
        ports:
          - 2289:2289
        options: >-
          --health-cmd "ps -a | grep legato"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: mstachniuk/ci-skip@v1
      with:
        fail-fast: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Run tests
      run: cd HarmonySDK.Tests && dotnet test --configuration Release
